# Generated by Django 5.0.6 on 2024-10-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_stripe_pid_alter_order_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
    ]
