# Generated by Django 5.0.6 on 2024-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
