# Generated by Django 5.0.6 on 2024-07-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='printful_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
