# Generated by Django 5.0.6 on 2024-11-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='printful_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sync_variant_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_id',
            field=models.CharField(max_length=255),
        ),
    ]
