# Generated by Django 5.0.6 on 2024-09-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_id',
            field=models.CharField(default='#66a36c387b2706', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
