# Generated by Django 5.0.6 on 2024-07-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_url_product_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image_url',
        ),
    ]
