# Generated by Django 5.0.6 on 2024-11-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_availability_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
